services:
  sysdocs:
    image: ghcr.io/georgstrassberger/sysdocs:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sysdocs.rule=Host(`docs.devops-zone.com`)"
      - "traefik.http.routers.sysdocs.entrypoints=websecure"
      - "traefik.http.routers.sysdocs.tls.certresolver=lets-encrypt"
      - "traefik.http.services.sysdocs.loadbalancer.server.port=4000"
    networks:
      - iotnetwork

networks:
  iotnetwork:
    external: true
